library(readr)
All_Years <- read_csv("All_Years.csv")
View(All_Years)

#imput missing vales
install.packages("mice")
library(mice)
set.seed(100)
DF.miss <- data.frame(All_Years[,c(3:56)])
mice_imputation <- mice(DF.miss, m = 5, maxit = 10, method = "pmm", seed = 100)
Complete_Data <- complete(mice_imputation,1)
DF1 <- data.frame(Complete_Data)
View(DF1)

#Data is ready for EDA and Modeling
#EDA
#Split DF1 into three parts for bating, fielding, and pitching statistics
DFB <- DF1[, c(23, 1:21)]
View(DFB)
summary(DFB)
DFP <- DF1[, c(23, 22, 24:43)]
View(DFP)
summary(DFP)
DFF <- DF1[, c(23, 44:54)]
View(DFF)
summary(DFF)

#Prepare to create Density Plots
DensityAVG <- density(DF1$AVG)
DensityERA <- density(DF1$ERA)
DensityFLDperc <- density(DF1$FLDperc)
DensityG <- density(DF1$G)
DensityAB <- density(DF1$AB)
DensityR <- density(DF1$R)
DensityH <- density(DF1$H)
DensityDOUBLES <- density(DF1$DOUBLES)
DensityTRIPLES <- density(DF1$TRIPLES)
DensityHR <- density(DF1$HR)
DensityRBI <- density(DF1$RBI)
DensityTB <- density(DF1$TB)
DensitySLGperc <- density(DF1$SLGperc)
DensityBB <- density(DF1$BB)
DensityHBP <- density(DF1$HBP)
DensitySO <- density(DF1$SO)
DensityGDP <- density(DF1$GDP)
DensityObperc <- density(DF1$Obperc)
DensitySF <- density(DF1$SF)
DensitySH <- density(DF1$SH)
DensitySBB <- density(DF1$SBB)
DensityATT <- density(DF1$ATT)
DensitySBB.ATTperc <- density(DF1$SBB.ATTperc)
DensityCG <- density(DF1$CG)
DensitySHO <- density(DF1$SHO)
DensityCBO <- density(DF1$CBO)
DensitySv <- density(DF1$SV)
DensityIP <- density(DF1$IP)
DensityHallowed <- density(DF1$Hallowed)
DensityRallowed <- density(DF1$Rallowed)
DensityER <- density(DF1$ER)
DensityBBallowed <- density(DF1$BBAllowed)
DensitySOfor <- density(DF1$SOfor)
DensityDOUBLESAllowed <- density(DF1$DOUBLESAllowed)
DensityTRIPLESAllowed <- density(DF1$TRIPLESAllowed)
DensityHRAllowed <- density(DF1$HRAllowed)
DensityABagainst <- density(DF1$Abagainst)
DensityAVGaginst <- density(DF1$AVGagainst)
DensityWP <- density(DF1$WP)
DensityHBPpitching <- density(DF1$HBPpitching)
DensityBK <- density(DF1$BK)
DensitySFA <- density(DF1$SFA)
DensitySHA <- density(DF1$SHA)
DensityC <- density(DF1$C)
DensityPO <- density(DF1$PO)
DensityA <- density(DF1$A)
DensityE <- density(DF1$E)
DensityDPs <- density(DF1$DPs)
DensitySBA <- density(DF1$SBA)
DensityCSB <- density(DF1$CSB)
DensitySBAperc <- density(DF1$SBAperc)
DensityPB <- density(DF1$PB)
DensityCI <- density(DF1$CI)

#Density Plots
par(mfrow = c(3,3))
plot(DensityAVG, xlab = "AVG", ylab = "Density", main = "Distribution of AVG", col = "blue")
plot(DensitySLGperc, xlab = "SLGperc", ylab = "Density", main = "Distrbution of SLGperc", col = "blue")
plot(DensityObperc, xlab = "Obperc", ylab = "Density", main = "Distribution of Obperc", col = "blue")
plot(DensityAB, xlab = "AB", ylab = "Density", main = "Distribution of AB", col = "blue")
plot(DensityR, xlab = "R", ylab = "Density", main = "Distribution of R", col = "blue")
plot(DensityH, xlab = "H", ylab = "Density", main = "Distribution of H", col = "blue")
plot(DensityDOUBLES, xlab = "DOUBLES", ylab = "Density", main = "Distribution of DOUBLES", col = "blue")
plot(DensityTRIPLES, xlab = "TRIPLES", ylab = "Density", main = "Distribution of Triples", col = "blue")
plot(DensityHR, xlab = "HR", ylab = "Density", main = "Distribution of HR", col = "blue")
par(mfrow = c(3,3))
plot(DensityRBI, xlab = "RBI", ylab = "Density", main = "Distribution of RBI", col = "blue")
plot(DensitySBB.ATTperc, xlab = "SBA.ATTperc", ylab = "Density", main = "Distribution of SBB.ATTperc", col = "blue")
plot(DensityTB, xlab = "TB", ylab = "Density", main = "Distribution of TB", col = "blue")
plot(DensitySF, xlab = "SF", ylab = "Density", main = "Distribution of SF", col = "blue")
plot(DensitySH, xlab = "SH", ylab = "Density", main = "Distribution of SH", col = "blue")
plot(DensityBB, xlab = "BB", ylab = "Density", main = "Distribution of BB", col = "blue")
plot(DensityHBP, xlab = "HBP", ylab = "Density", main = "Distribution of HBP", col = "blue")
plot(DensitySO, xlab = "So", ylab = "Density", main = "Distribution of SO", col = "blue")
plot(DensityGDP, xlab = "GDP", ylab = "Density", main = "Distribution of GDP", col = "blue")
par(mfrow = c(2,1))
plot(DensitySBB, xlab = "SBB", ylab = "Density", main = "Distribution of SBB", col = "blue")
plot(DensityATT, xlab = "ATT", ylab = "Density", main = "Distribution of ATT", col = "blue")
par(mfrow = c(3,3))
plot(DensityERA, xlab = "ERA", ylab = "Density", main = "Distribution of ERA", col = "blue")
plot(DensityCG, xlab = "CG", ylab = "Density", main = "Distribution of CG", col = "blue")
plot(DensitySHO, xlab = "SHO", ylab = "Density", main = "Distribution of SHO", col = "blue")
plot(DensityCBO, xlab = "CBO", ylab = "Density", main = "Distribution of CBO", col = "blue")
plot(DensitySv, xlab = "SV", ylab = "Density", main = "Distribution of SV", col = "blue")
plot(DensityIP, xlab = "IP", ylab = "Density", main = "Distribution of IP", col = "blue")
plot(DensityHallowed, xlab = "Hallowed", ylab = "Density", main = "Distribution of Hallowed", col = "blue")
plot(DensityRallowed, xlab = "Rallowed", ylab = "Density", main = "Distribution of Rallowed", col = "blue")
plot(DensityER, xlab = "ER", ylab = "Density", main = "Distribution of ER", col = "blue")
par(mfrow = c(3,3))
plot(DensityBBallowed, xlab = "BBallowed", ylab = "Density", main = "Distribution of BBallowed", col = "blue")
plot(DensitySOfor, xlab = "SOfor", ylab = "Density", main = "Distribution of SOfor", col = "blue")
plot(DensityDOUBLESAllowed, xlab = "DOUBLESAllowed", ylab = "Density", main = "Distribution of DOUBLESAllowed", col = "blue")
plot(DensityTRIPLESAllowed, xlab = "TRIPLESAllowed", ylab = "Density", main = "Distribution of TRIPLESAllowed", col = "blue")
plot(DensityHRAllowed, xlab = "HRAllowed", ylab = "Density", main = "Distribution of HRAllowed", col = "blue")
plot(DensityABagainst, xlab = "ABagainst", ylab = "Density", main = "Distribution of ABagainst", col = "blue")
plot(DensityAVGaginst, xlab = "AVGagainst", ylab = "Density", main = "Distribution of AVGagainst", col = "blue")
plot(DensityWP, xlab = "WP", ylab = "Density", main = "Distribution of WP", col = "blue")
plot(DensityHBPpitching, xlab = "HBPpitching", ylab = "Density", main = "Distribution of HBPpitching", col = "blue")
par(mfrow = c(3,1))
plot(DensityBK, xlab = "BK", ylab = "Density", main = "Distribution of BK", col = "blue")
plot(DensitySFA, xlab = "SFA", ylab = "Density", main = "Distribution of SFA", col = "blue")
plot(DensitySHA, xlab = "SHA", ylab = "Density", main = "Distribution of SHA", col = "blue")
par(mfrow = c(2,2))
plot(DensityC, xlab = "C", ylab = "Density", main = "Distribution of C", col = "blue")
plot(DensityPO, xlab = "PO", ylab = "Density", main = "Distribution of PO", col = "blue")
plot(DensityA, xlab = "A", ylab = "Density", main = "Distribution of A", col = "blue")
plot(DensityE, xlab = "E", ylab = "Density", main = "Distribution of E", col = "blue")
par(mfrow = c(2,2))
plot(DensityFLDperc, xlab = "FLDperc", ylab = "Density", main = "Distribution of FLDperc", col = "blue")
plot(DensityDPs, xlab = "DPs", ylab = "Density", main = "Distribution of DPs", col = "blue")
plot(DensitySBA, xlab = "SBA", ylab = "Density", main = "Distribution of SBA", col = "blue")
plot(DensityCSB, xlab = "CSB", ylab = "Density", main = "Distribution of CSB", col = "blue")
par(mfrow = c(3,1))
plot(DensityPB, xlab = "PB", ylab = "Density", main = "Distribution of PB", col = "blue")
plot(DensityCI, xlab = "CI", ylab = "Density", main = "Distribution of CI", col = "blue")
plot(DensitySBAperc, xlab = "SBAperc", ylab = "Density", main = "Distribution of SBAperc", col = "blue")

#Spearman correlation tables for each category of statistics
CORRBATT <- cor(DFB, use = "complete.obs", method = "spearman")
DF_CORRBATT <- data.frame(sort(CORRBATT[,1], decreasing = TRUE))
View(DF_CORRBATT)
write.csv(DF_CORRBATT, "DF_CORRBATT.csv")
CORRFLD <- cor(DFF, use = "complete.obs", method = "spearman")
DF_CORRFLD <- data.frame(sort(CORRFLD[,1], decreasing = TRUE))
View(DF_CORRFLD)
write.csv(DF_CORRFLD, "DF_CORRFLD.csv")
CORRPITCH <- cor(DFP, use = "complete.obs", method = "spearman")
DF_CORRPITCH <- data.frame(sort(CORRPITCH[,1], decreasing = TRUE))
View(DF_CORRPITCH)
write.csv(DF_CORRPITCH, "DF_CORRPITCH.csv")
CORRALL <- cor(DF1, use = "complete.obs", method = "spearman")
DF_CORRALL <- data.frame(sort(CORRALL[,23], decreasing = TRUE))
View(DF_CORRALL)
write.csv(DF_CORRALL, "DF_CORRALL.csv")

#Plots for the most highly correlated variables from each category
install.packages("ggpubr")
library(ggpubr)
Scatter_R <- ggscatter(DF1, x = "R", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "R", ylab = "W", title = "Runs Scored Correlation with Wins")
Scatter_RBI <- ggscatter(DF1, x = "RBI", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "RBI", ylab = "W", title = "RBI Correlation with Wins")
Scatter_TB <- ggscatter(DF1, x = "TB", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "TB", ylab = "W", title = "Total Bases Correlation to Wins")
ggarrange(Scatter_R, Scatter_RBI, Scatter_TB, ncol = 1, nrow = 3)
Scatter_AVGagainst <- ggscatter(DF1, x = "AVGagainst", y = "W", add = "reg.line" , cor.coef = TRUE, cor.method = "spearman", xlab = "AVGagainst", ylab = "W", title = "AVGagainst Correlation with Wins")
Scatter_IP <- ggscatter(DF1, x = "IP", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "IP", ylab = "W", title = "IP Correlation with Wins")
Scatter_SOfor <- ggscatter(DF1, x = "SOfor", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "SOfor", ylab = "W", title = "SOfor Correlation with Wins")
ggarrange(Scatter_AVGagainst, Scatter_IP, Scatter_SOfor, ncol = 1, nrow = 3)
Scatter_PO <- ggscatter(DF1, x = "PO", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "PO", ylab = "W", title = "Put Outs Correlation with Wins")
Scatter_C <- ggscatter(DF1, x = "C", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "C", ylab = "W", title = "Total Chances Correlation with Wins")
Scatter_A <- ggscatter(DF1, x = "A", y = "W", add = "reg.line", cor.coef = TRUE, cor.method = "spearman", xlab = "A", ylab = "W", title = "Assists Correlation with Wins")
ggarrange(Scatter_PO, Scatter_C,Scatter_A, ncol = 1, nrow = 3)

#Random Forest
set.seed(100)
training <- sample(nrow(DF1), 0.70*nrow(DF1), replace = TRUE)
Train <- DF1[training,]
Test <- DF1[-training,]
install.packages("randomForest")
library(randomForest)
RF.wins_withmice <- randomForest(W~., data = Train, importance = TRUE)
print(RF.wins_withmice)
Importance <- data.frame(importance(RF.wins_withmice, type = 1))
write.csv(Importance, "Variable_Importance_Table.csv")
varImpPlot(RF.wins_withmice, type = 1, main = "Variable Importance")

#Create tables to analyze predictions vs actual number of wins
install.packages("caret")
library(caret)
prediction <- predict(RF.wins_withmice, newdata = Test)
print(prediction)
Prediction <- data.frame(prediction)
DF_Wins_Test <- Test[,23, drop = FALSE]
Prediction_vs_Actual <- cbind(Prediction, DF_Wins_Test)
View(Prediction_vs_Actual)
Prediction_All <- predict(RF.wins_withmice, newdata = DF1)
print(Prediction_All)
Prediction_All_DF <- data.frame(Prediction_All)
DF_Wins_All <- DF1[,23, drop = FALSE]
Predictions_All_vs_Actual_All <- cbind(Prediction_All_DF, DF_Wins_All)
DF_Names_and_Year <- All_Years[,1:2, drop = FALSE]
Prediction_Final_DF <- cbind(Predictions_All_vs_Actual_All, DF_Names_and_Year)
View(Prediction_Final_DF)
install.packages("readxl")
library(readxl)
Rank_Column <- read_excel("Rank_Column.xlsx")
Final_Predictions_with_Ranks <- cbind(Prediction_Final_DF, Rank_Column)
View(Final_Predictions_with_Ranks)
DF_Final_Predictions_with_Ranks <- data.frame(Final_Predictions_with_Ranks)
write.csv(DF_Final_Predictions_with_Ranks, "Final_Predictions_with_Ranks.csv")
VarImportance_withmice <- data.frame(sort(importance(RF.wins_withmice)[,1], decreasing = TRUE))

#Create Excel file for analysis
DF_Important <- DF1[, c(23, 28, 45, 38, 33, 5, 22, 4, 10, 3, 9)]
View(DF_Important)
DF_Important_Names_and_Year <- cbind(DF_Important, DF_Names_and_Year)
View(DF_Important_Names_and_Year)
DF_Important_Names_and_Year <- cbind(DF_Names_and_Year, DF_Important)
DF_Important_with_Ranks <- cbind(DF_Important_Names_and_Year, Rank_Column)
View(DF_Important_with_Ranks)
write.csv(DF_Important_with_Ranks, "DF_Important_with_Ranks.csv")

